name: 'Custom steps to run after R packages are installed'

runs:
  using: "composite"
  steps:
    - name: Define R CMD check error condition
      run: |
        if (getRversion() < "4.0") {
          message("Setting RCMDCHECK_ERROR_ON")
          cat('RCMDCHECK_ERROR_ON="warning"\n', file = Sys.getenv("GITHUB_ENV"), append = TRUE)
        }
      shell: Rscript {0}

    - name: Install knitcitations if needed
      run: |
        pak::pak("cboettig/knitcitations")
      shell: Rscript {0}
