name: 'Custom steps to run after R packages are installed'

runs:
  using: "composite"
  steps:
    - name: Compute ccache key
      run: |
        echo "GHA_CCACHE_KEY=${{ runner.os }}-$($(R CMD config CXX) --version | head -n 1 | sed -r 's/[, ]/-/g')-R-$(Rscript --vanilla -e 'cat(format(getRversion()))')" | tee -a $GITHUB_ENV
      shell: bash

    - name: Install persistent ccache
      uses: hendrikmuhs/ccache-action@v1.2.10
      with:
        key: ${{ env.GHA_CCACHE_KEY }}
        max-size: 200M
        verbose: 1

    - name: Install to avoid R CMD INSTALL --pre-clean run otherwise
      run: |
        mkdir ../lib
        R CMD INSTALL --library=$(dirname $(pwd))/lib -d --no-byte-compile .
      shell: bash

    - name: Show ccache stats
      run: |
        ccache -s
      shell: bash
