name: 'Custom steps to run after R packages are installed'

runs:
  using: "composite"
  steps:
    # Must happen after R is installed...
    - name: Define R CMD check error condition
      run: |
        if (packageVersion("arrow") < "8.0.0") {
          message("Setting RCMDCHECK_ERROR_ON = error")
          cat('RCMDCHECK_ERROR_ON="error"\n', file = Sys.getenv("GITHUB_ENV"), append = TRUE)
        } else if (getRversion() < "3.5") {
          message("Setting RCMDCHECK_ERROR_ON = warning")
          cat('RCMDCHECK_ERROR_ON="warning"\n', file = Sys.getenv("GITHUB_ENV"), append = TRUE)
        }
      shell: Rscript {0}

    - name: Define _R_CHECK_FORCE_SUGGESTS_
      run: |
        if (getRversion() < "3.5") {
          message("Setting _R_CHECK_FORCE_SUGGESTS_")
          cat('_R_CHECK_FORCE_SUGGESTS_=false\n', file = Sys.getenv("GITHUB_ENV"), append = TRUE)
        }
      shell: Rscript {0}
