name: 'Actions to run after R packages are installed'

runs:
  using: "composite"
  steps:
    # Must happen after installing system dependencies,
    # https://github.com/ankane/setup-mariadb/issues/2
    - uses: ankane/setup-mariadb@v1
      with:
        mariadb-version: 10.5

    - name: Create database, set it to UTF-8
      run: |
        mysql -e "CREATE DATABASE IF NOT EXISTS test; ALTER DATABASE test CHARACTER SET 'utf8'; FLUSH PRIVILEGES;"
