name: 'Custom steps to run after R packages are installed'

runs:
  using: "composite"
  steps:
    - name: Define R CMD check error condition
      run: |
        # metap is a suggested package that is difficult to install for old R versions;
        # if it is not available, we will see a NOTE mentioning this.
        if (!requireNamespace("metap", quietly = TRUE)) {
          message("Setting RCMDCHECK_ERROR_ON")
          cat('RCMDCHECK_ERROR_ON="warning"\n', file = Sys.getenv("GITHUB_ENV"), append = TRUE)
        }
      shell: Rscript {0}

    - name: Install knitcitations if needed
      env:
        GITHUB_PAT: ${{ github.token }}
      run: |
        pak::pak("cboettig/knitcitations")
      shell: Rscript {0}
