name: fledge

on:
  # for manual triggers
  workflow_dispatch:
  # for debugging
  push:
    paths:
      - .github/workflows/fledge.yaml
  # daily run
  schedule:
  - cron: "30 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}
  cancel-in-progress: true

jobs:
  fledge:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      FLEDGE_GHA_CI: true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: ./.github/workflows/git-identity

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: local::.

      - name: Bump version
        run: |
          fledge::bump_version(which = "dev", no_change_behavior = "noop")
          fledge::finalize_version(push = TRUE)
        shell: Rscript {0}
