name: fledge

on:
  # for manual triggers
  workflow_dispatch:
  # daily run
  schedule:
  - cron: "0 8 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || github.sha }}-${{ github.base_ref || '' }}
  cancel-in-progress: true

jobs:
  call-dm-fledge:
    uses: cynkra/dm/.github/workflows/fledge.yaml@main
