---
output:
  html_document:
    self_contained: false
title: "Repository status"
---

```{r include = FALSE}
github <- Sys.getenv("GITHUB_SERVER_URL", "https://github.com")
gen_slug <- Sys.getenv("GITHUB_REPOSITORY")

library(dplyr)
library(purrr)
```

Generated by [`r gen_slug`](`r github`/`r gen_slug`).


```{r echo = FALSE}
all_workflows <- dir("wt", recursive = TRUE)
repo_workflows <- grep("^[^/]+/[^/]+/[^/]+[.]ya?ml$", all_workflows, value = TRUE)

has_push <- function(x) {
  if (is.character(x)) {
    "push" %in% x
  } else {
    !is.null(x$push)
  }
}

make_slug <- function(slug) {
  paste0(
    '<a href="', github, "/", slug, '" target="_blank">',
    slug,
    "</a>",
    ' <a href="', github, "/", slug, '/actions" target="_blank">',
    "(actions)",
    "</a>"
  )
}

make_badge <- function(slug, name, yaml_name) {
  paste0(
    '<a href="', github, "/", slug, "/actions/workflows/", yaml_name, '" target="_blank">',
    "![", name, "]",
    "(https://shields.io/github/actions/workflow/status/", slug, "/", yaml_name, "?label=", name, ")",
    "</a>"
  )
}

tibble(workflow = repo_workflows) %>%
  mutate(contents = map(file.path("wt", workflow), ~ suppressWarnings(yaml::read_yaml(.x, eval.expr = FALSE)))) %>%
  mutate(has_push = map_lgl(contents, ~ has_push(.x$on) || has_push(.x$"TRUE"))) %>%
  filter(has_push) %>%
  mutate(name = map_chr(contents, c("name"))) %>%
  mutate(yaml_name = basename(workflow)) %>%
  mutate(name = coalesce(name, yaml_name)) %>%
  mutate(slug = dirname(workflow)) %>%
  add_count(name) %>%
  arrange(slug, desc(n), name) %>%
  select(slug, name, yaml_name) %>%
  group_by(slug) %>%
  summarize(badge = paste(make_badge(slug, name, yaml_name), collapse = " ")) %>%
  ungroup() %>%
  transmute(Repository = make_slug(slug), Badges = badge) %>%
  knitr::kable()
```
