# Workflow to update the status of a commit for the R-CMD-check workflow
# Necessary because remote PRs cannot update the status of the commit
on:
  workflow_run:
    workflows:
      - rcc
    types:
      - requested
      - completed

name: rcc-status

jobs:
  rcc-status:
    runs-on: ubuntu-latest

    name: "Update commit status"

    # Only run if triggered by rcc workflow
    if: github.event.workflow_run.name == 'rcc'

    steps:
      - name: "Update commit status"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          sha=${{ github.event.workflow_run.head_sha }}

          if [ "${{ github.event.workflow_run.status }}" == "completed" ]; then
            if [ "${{ github.event.workflow_run.conclusion }}" == "success" ]; then
              state="success"
            else
              state="failure"
            fi
          else
            state="pending"
          fi

          html_url=${{ github.event.workflow_run.html_url }}
          description=${{ github.event.workflow_run.name }}

          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            repos/${{ github.repository }}/statuses/${sha} \
            -f "state=${state}" -f "target_url=${html_url}" -f "description=${description}" -f "context=rcc"
        shell: bash
