# This workflow calls the GitHub API very frequently.
# Can't be run as part of commits
on:
  schedule:
    - cron:  '0 1 * * *'
  push:
    paths:
      - ".github/workflows/R-CMD-check-dev.yaml"

name: rcc dev

jobs:
  matrix:
    runs-on: ubuntu-18.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    name: Collect deps

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/bionic/latest
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      # prevent rgl issues because no X11 display is available
      RGL_USE_NULL: true
      # Begin custom: env vars
      # End custom: env vars

    steps:
      - name: Check rate limits
        run: |
          curl -s --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/rate_limit
        shell: bash

      - uses: actions/checkout@v2

      - id: set-matrix
        run: |
          # From remotes
          has_dev_dep <- function(package) {
            cran_url <- "https://cloud.r-project.org"

            refs <- dev_split_ref(package)
            url <- build_url(cran_url, "web", "packages", refs[["pkg"]], "DESCRIPTION")

            f <- tempfile()
            on.exit(unlink(f))

            download(f, url)
            desc <- read_dcf(f)

            url_fields <- c(desc$URL, desc$BugReports)

            if (length(url_fields) == 0) {
              return(FALSE)
            }

            pkg_urls <- unlist(strsplit(url_fields, "[[:space:]]*,[[:space:]]*"))

            # Remove trailing "/issues" from the BugReports URL
            pkg_urls <- sub("/issues$", "", pkg_urls)

            valid_domains <- c("github[.]com", "gitlab[.]com", "bitbucket[.]org")

            parts <-
              re_match(pkg_urls,
                sprintf("^https?://(?<domain>%s)/(?<username>%s)/(?<repo>%s)(?:/(?<subdir>%s))?",
                  domain = paste0(valid_domains, collapse = "|"),
                  username = "[^/]+",
                  repo = "[^/@#]+",
                  subdir = "[^/@$ ]+"
                )
              )[c("domain", "username", "repo", "subdir")]

            # Remove cases which don't match and duplicates

            parts <- unique(stats::na.omit(parts))

            nrow(parts) == 1
          }

          dir.create(".github/lib")
          .libPaths(".github/lib")

          install.packages("remotes")
          deps <- remotes::dev_package_deps(dependencies = TRUE)
          packages <- deps$package

          valid_dev_dep <- vapply(packages, has_dev_dep, logical(1))

          deps <- sort(packages[valid_dev_dep])
          if (any(!valid_dev_dep)) {
            msg <- paste0(
              "Could not determine development repository for packages: ",
              paste(packages[!valid_dev_dep], collaspe = ", ")
            )
            writeLines(paste0("::warning::", msg))
          }

          json <- paste0(
            '{"package":[',
            paste0('"', deps, '"', collapse = ","),
            ']}'
          )
          writeLines(json)
          writeLines(paste0("::set-output name=matrix::", json))
        shell: Rscript {0}

  check-matrix:
    runs-on: ubuntu-18.04
    needs: matrix
    steps:
      - name: Install json2yaml
        run: |
          sudo npm install -g json2yaml

      - name: Check matrix definition
        run: |
          matrix='${{ needs.matrix.outputs.matrix }}'
          echo $matrix
          echo $matrix | jq .
          echo $matrix | json2yaml
