# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
#
# NOTE: This workflow is overkill for most R packages and
# check-standard.yaml is likely a better choice.
# usethis::use_github_action("check-standard") will install it.
on:
  push:
    branches:
      - main
      - master
      - "r-*"
  pull_request:
    branches:
      - main
      - master
      - "r-*"
  schedule:
    - cron:  '10 0 * * *'

name: rcc

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }}) ${{ matrix.config.desc }}

    # Begin custom: services
    # End custom: services

    strategy:
      fail-fast: false
      # Ensure that the "cancel" workflow gets a chance to run quickly, even if we just pushed
      # Need to figure out how to smoke-test
      max-parallel: 5
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/workflows/rate-limit
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/workflows/custom/before-install

      - uses: ./.github/workflows/install
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/workflows/custom/after-install

      - uses: ./.github/workflows/check

      - uses: ./.github/workflows/rate-limit
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
