# This workflow creates many jobs, run only when a branch is created
on:
  push:
    branches:
      - "revdep*"

name: revdep

jobs:
  matrix:
    runs-on: ubuntu-18.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    name: Collect revdeps

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/bionic/latest
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      # prevent rgl issues because no X11 display is available
      RGL_USE_NULL: true
      # Begin custom: env vars
      # End custom: env vars

    steps:
      - name: Check rate limits
        run: |
          curl -s --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/rate_limit
        shell: bash

      - uses: actions/checkout@v2

      # FIXME: Avoid reissuing succesful jobs
      # https://docs.github.com/en/free-pro-team@latest/rest/reference/actions#list-jobs-for-a-workflow-run
      # https://docs.github.com/en/free-pro-team@latest/rest/reference/actions#workflow-runs
      - id: set-matrix
        run: |
          package <- read.dcf("DESCRIPTION")[, "Package"][[1]]
          deps <- tools:::package_dependencies(package, reverse = TRUE, which = c("Depends", "Imports", "LinkingTo", "Suggests"))[[1]]
          json <- paste0(
            '{"package":[',
            paste0('"', deps, '"', collapse = ","),
            ']}'
          )
          writeLines(json)
          writeLines(paste0("::set-output name=matrix::", json))
        shell: Rscript {0}

  check-matrix:
    runs-on: ubuntu-18.04
    needs: matrix
    steps:
      - name: Install json2yaml
        run: |
          sudo npm install -g json2yaml

      - name: Check matrix definition
        run: |
          matrix='${{ needs.matrix.outputs.matrix }}'
          echo $matrix
          echo $matrix | jq .
          echo $matrix | json2yaml

  R-CMD-check:
    needs: matrix

    runs-on: ubuntu-18.04

    name: ${{ matrix.package }}

    # Begin custom: services
    # End custom: services

    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.matrix.outputs.matrix)}}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/bionic/latest
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      # prevent rgl issues because no X11 display is available
      RGL_USE_NULL: true
      # Begin custom: env vars
      # End custom: env vars

    steps:
      - name: Dummy
        run: |
          echo ${{ matrix.package }}
        shell: bash
