# This workflow creates many jobs, run only when a branch is created
on:
  push:
    branches:
      - "revdep*"

name: revdep

jobs:
  R-CMD-check:
    runs-on: ubuntu-18.04

    name: ${{ matrix.package }}

    # Begin custom: services
    # End custom: services

    strategy:
      fail-fast: false
      matrix:
        package:
          - DBI
          - DBItest
          - E4tools
          - MEDITS
          - RMariaDB
          - RPostgres
          - ari
          - arrow
          - bigrquery
          - checkr
          - dbx
          - dttr2
          - eatGADS
          - edeaR
          - eplusr
          - extras
          - feather
          - gtfsrouter
          - haven
          - hmstimer
          - mudata2
          - odbc
          - processmapR
          - progress
          - ratPASTA
          - readr
          - readwritesqlite
          - rwalkr
          - scales
          - tibble
          - tibbletime
          - tidytransit
          - tidyverse
          - timetk
          - tsibble
          - tuber
          - vroom

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/bionic/latest
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      # prevent rgl issues because no X11 display is available
      RGL_USE_NULL: true
      # Begin custom: env vars
      # End custom: env vars

    steps:
      - name: Dummy
        run: |
          echo ${{ matrix.package }}
        shell: bash
