# Synchronize with https://github.com/krlmlr/r-actions-subtree
on:
  push:
    branches:
      - main
      - master
    paths:
      - '.github/workflows/**'

name: Sync workflows

jobs:
  R-CMD-check:
    runs-on: ubuntu-18.04

    name: Push workflows subtree

    steps:
      - uses: actions/checkout@v2

      - name: git subtree push
        run: |
          git subtree push --prefix=.github/workflows https://${{ secrets.GITHUB_TOKEN }}@github.com/krlmlr/r-actions-subtree ${{ env.GITHUB_REPOSITORY }}
        shell: bash
