on:
  push:
    paths:
      - .github/workflows/windows-tests.yaml
      - tests/testthat/_snaps/*

name: windows-tests

jobs:
  tests:
    runs-on: windows-latest
    defaults:
      run:
        shell: Rscript {0}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
        with:
          install-r: false

      - name: Edit Git config
        run: |
          git log -n 1 --pretty=format:"git config user.name '%an'; git config user.email '%ae'" | sh
        shell: bash

      - name: Query dependencies
        run: |
          install.packages("remotes")
          saveRDS(remotes::dev_package_deps(dependencies = TRUE, type = "binary"), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE, type = "binary")

      - name: Run tests, allow failures
        run: |
          testthat::test_local(stop_on_failure = FALSE)
          testthat::snapshot_accept()

      - name: Commit and push
        run: |
          git status
          git status tests/testthat/_snaps
          git status --porcelain tests/testthat/_snaps
          if [[ $(git status --porcelain tests/testthat/_snaps) == "" ]]
          then
            echo "No changes to commit"
          else
            git add tests/testthat/_snaps
            git commit -m "Add Windows snapshot output"
            git push origin
          fi
        shell: bash
