name: 'Action to auto-style a package'

runs:
  using: "composite"
  steps:
    - name: Debug styler options
      run: |
        set -x
        scope=$(grep Config/autostyle/scope DESCRIPTION | cut -d " " -f 2)
        strict=$(grep Config/autostyle/strict DESCRIPTION | cut -d " " -f 2)
        echo $scope
        echo $strict
      shell: Rscript {0}

    - name: Check styler options
      id: check
      run: |
        set -x
        scope=$(grep Config/autostyle/scope DESCRIPTION | cut -d " " -f 2)
        strict=$(grep Config/autostyle/strict DESCRIPTION | cut -d " " -f 2)
        echo ::set-output name=scope::$scope
        echo ::set-output name=strict::$strict
      shell: Rscript {0}

    - name: Enable styler cache
      if: ${{ steps.check.outputs.scope }}
      run: |
        styler::cache_activate(verbose = TRUE)
      shell: Rscript {0}

    - name: Run styler
      if: ${{ steps.check.outputs.scope }} && !${{ steps.check.outputs.strict }}
      run: |
        styler::style_pkg(scope = "${{ steps.check.outputs.scope }}", strict = FALSE)
      shell: Rscript {0}

    - name: Run strict styler
      if: ${{ steps.check.outputs.scope }} && ${{ steps.check.outputs.strict }}
      run: |
        styler::style_pkg(scope = "${{ steps.check.outputs.scope }}", strict = TRUE)
      shell: Rscript {0}
