name: "Action to commit changes to the repository"
inputs:
  token:
    description: "GitHub token"
    required: true
outputs:
  sha:
    description: "SHA of generated commit"
    value: ${{ steps.commit.outputs.sha }}

runs:
  using: "composite"
  steps:
    - name: Commit if changed, create a PR if protected
      id: commit
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        set -x
        if [ -n "$(git status --porcelain)" ]; then
          echo "Changed"
          protected=${{ github.ref_protected }}
          foreign=${{ github.event.pull_request.head.repo.full_name != github.repository }}
          if [ "${foreign}" = "true" ]; then
            # https://github.com/krlmlr/actions-sync/issues/44
            echo "Can't push to foreign branch"
          else if [ "${protected}" = "true" ]; then
            current_branch=$(git branch --show-current)
            new_branch=gha-commit-$(git rev-parse --short HEAD)
            git checkout -b ${new_branch}
            git add .
            git commit -m "chore: Auto-update from GitHub Actions"$'\n'$'\n'"Run: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
            # Force-push, collisions are unlikely
            git push -u origin HEAD -f

            existing_pr=$(gh pr list --state open --base main --head ${new_branch} --json number --jq '.[] | .number')
            if [ -n "${existing_pr}" ]; then
              echo "Existing PR: ${existing_pr}"
            else
              gh pr create --base main --head ${new_branch} --title "chore: Auto-update from GitHub Actions" --body "Run: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
            fi

            gh pr merge --merge --auto
          else
            git fetch
            if [ -n '${{ github.head_ref }}' ]; then
              # Find the name of the remote of the PR's source
              remote_repo=${{ github.event.pull_request.head.repo.clone_url }}
              git remote add pr-source $remote_repo
              git fetch pr-source ${{ github.head_ref }}
              git add .
              git stash save
              git switch ${GITHUB_HEAD_REF}
              git merge origin/${GITHUB_BASE_REF} --no-edit
              git stash pop
              remote=pr-source
            else
              remote=origin
            fi
            git add .
            git commit -m "chore: Auto-update from GitHub Actions"$'\n'$'\n'"Run: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
            git push -u ${remote} HEAD
            if [ "${remote}" = "pr-source" ]; then
              git remote remove ${remote}
            fi
          fi
          # Only set output if changed
          echo sha=$(git rev-parse HEAD) >> $GITHUB_OUTPUT
        fi
      shell: bash
