name: "Actions to read a matrix with all suggested packages, computed with the dep-suggests-matrix action"
outputs:
  matrix:
    description: "Generated matrix"
    value: ${{ steps.set-matrix.outputs.matrix }}

runs:
  using: "composite"
  steps:
    - name: Install json2yaml
      run: |
        sudo npm install -g json2yaml
      shell: bash

    - id: set-matrix
      run: |
        # Empty contents if no suggested packages
        matrix=$(cat .github/dep-suggests-matrix.json || true)

        # Empty contents if no changes in tests
        if [ -n "${GITHUB_BASE_REF}" ]; then
          if ! git diff ${{ github.event.pull_request.base.sha }}... | egrep '^[+][^+]' | grep -q ::; then
            echo "No changes using :: found, not checking without suggested packages"
            matrix=""
          fi
        fi

        if [ -n "$matrix" ]; then
          echo $matrix | jq .
          echo $matrix | json2yaml
        fi
        echo "matrix=$matrix" | tee -a $GITHUB_OUTPUT
      shell: bash
