name: 'Custom steps to run before R packages are installed'

runs:
  using: "composite"
  steps:
    - name: Define R CMD check error condition
      run: |
        echo '_R_CHECK_PKG_SIZES_=FALSE' | tee -a $GITHUB_ENV
      shell: bash

    - name: Install and use GLPK on macOS
      if: runner.os == 'macOS'
      run: |
        brew install glpk
        echo -e 'CPPFLAGS = -I/opt/homebrew/include\nLDFLAGS = -L/opt/homebrew/lib' | tee ~/.R/Makevars
      shell: bash
