name: 'Actions to run before R packages are installed'

runs:
  using: "composite"
  steps:
    - name: Install libunwind
      if: runner.os == 'Linux' && matrix.config.libunwind != 'omit-libunwind'
      env:
        RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
      run: |
        sudo apt-get update
        sudo apt-get install -y libunwind-dev

    - name: Break libbacktrace
      if: matrix.config.libbacktrace == 'omit-libbacktrace'
      run: |
        echo '{ print "bogus"; exit }' > src/vendor/libbacktrace/filetype.awk
