name: 'Actions to run before R packages are installed'

runs:
  using: "composite"
  steps:
    # FIXME: Remove with cran units > 0.7.2
    - name: Install system dependencies
      if: runner.os == 'macOS'
      run: |
        brew install udunits
