name: 'Actions to run before R packages are installed'

runs:
  using: "composite"
  steps:
    - name: Empty
      run: |
        sudo apt-get update
        sudo apt-get install -y libgit2-dev
      shell: bash
