name: 'Custom steps to run before R packages are installed'

runs:
  using: "composite"
  steps:
    - name: Install protobuf
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libprotoc-dev libprotobuf-dev protobuf-compiler
      shell: bash

