name: 'Actions to run before R packages are installed'

runs:
  using: "composite"
  steps:
    - name: Prepare Bioconductor
      run: |
        if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager")
        cat("options(repos = BiocManager::repositories())\n", file = "~/.Rprofile", append = TRUE)
      shell: Rscript {0}

    - name: Define R CMD check error condition
      run: |
        if (getRversion() < "4.0") {
          message("Setting RCMDCHECK_ERROR_ON")
          cat('RCMDCHECK_ERROR_ON="warning"\n', file = Sys.getenv("GITHUB_ENV"), append = TRUE)
        }
      shell: bash
