name: 'Custom steps to run before R packages are installed'

runs:
  using: "composite"
  steps:
    - name: Install JAGS macOS
      if: runner.os == 'macOS'
      run: |
        brew install jags
      shell: bash

    - name: Download JAGS Windows
      if: runner.os == 'Windows'
      run: |
        (New-Object System.Net.WebClient).DownloadFile('https://sourceforge.net/projects/mcmc-jags/files/JAGS/4.x/Windows/JAGS-4.3.1.exe', 'C:\JAGS-4.3.1.exe')
      shell: powershell

    - name: Install JAGS Windows
      if: runner.os == 'Windows'
      run: |
        C:\JAGS-4.3.1.exe /S
      shell: cmd
