name: 'Update status'
description: 'Update status'
inputs:
  sha:
    description: 'SHA to update'
    required: true
  state:
    description: 'state to update'
    required: true

runs:
  using: "composite"
  steps:
    # It's difficult to get the URL of the current job.
    # The /jobs API and/or the `github` context are misaligned.
    # The duckdbneo repository contains several failed attempts.
    - run: |
        set -x
        if [ -n ${{ inputs.sha }} ]; then
          export GH_TOKEN=${{ github.token }}
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/statuses/${{ inputs.sha }} \
            -f "state=${{ job.status }}" -f "description=${{ github.job_id }}" -f "context=actions-sync"

          env | sort

          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs

          # html_url=$(gh api \
          #   -H "Accept: application/vnd.github+json" \
          #   -H "X-GitHub-Api-Version: 2022-11-28" \
          #   /repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs | jq . | tee /dev/stderr | jq '.jobs[] | select (.name == ${{ github.job }}) | .html_url')

          # echo $html_url

          # curl -f -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ github.token }}" https://api.github.com/repos/${{ github.repository }}/statuses/${{ inputs.sha }} -d '{"state": "${{ inputs.state }}", "context": "${{ github.workflow }} / ${{ github.job }}", "target_url": '${html_url}' }'
        fi
      shell: bash
