name: 'Update status'
description: 'Update status'
inputs:
  sha:
    description: 'SHA to update'
    required: true
  state:
    description: 'state to update'
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        set -x
        if [ -n ${{ inputs.sha }} ]; then
          html_url=$(curl -f -s -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ github.token }}" https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs | jq '.jobs[] | select (.name == env.GITHUB_JOB) | .html_url')
          curl -f -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ github.token }}" https://api.github.com/repos/${{ github.repository }}/statuses/${{ inputs.sha }} -d '{"state": "${{ inputs.state }}", "context": "${{ github.workflow }} / ${{ github.job }}", "target_url": '${html_url}' }'
        fi
      shell: bash
