name: 'Update status'
description: 'Update status'
inputs:
  sha:
    description: 'SHA to update'
    required: true
  context:
    description: 'Context to update'
    required: true

runs:
  using: "composite"
  steps:
    # It's difficult to get the URL of the current job.
    # The /jobs API and/or the `github` context are misaligned.
    # The duckdbneo repository contains several failed attempts.
    - run: |
        set -x
        sha=${{ inputs.sha }}
        # If no SHA is provided, use the current commit
        if [ -z '${{ inputs.sha }}' ]; then
          if [ -n '${{ github.head_ref }}' ]; then
            sha=$(git rev-parse origin/${{ github.head_ref }})
          else
            sha=$(git rev-parse HEAD)
          fi
        fi

        export GH_TOKEN=${{ github.token }}

        html_url=$(gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          repos/${{ github.repository }}/actions/runs/${{ github.run_id }} | jq -r .html_url)

        # Check if a failing status has been set already
        status=$(gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          repos/${{ github.repository }}/commits/${sha}/status | jq -r .state)

        if [ "${status}" != "error" ] && [ "${status}" != "failure" ]; then
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            repos/${{ github.repository }}/statuses/${sha} \
            -f "state=${{ job.status }}" -f "target_url=$html_url" -f "description=${{ github.workflow }} / ${{ github.job }}" -f "context=${{ inputs.context }}"
        fi
      shell: bash
