name: 'Actions to run before R packages are installed'
inputs:
  matrix_config:
    description: Build matrix, pass matrix.config
    required: true

runs:
  using: "composite"
  steps:
    - name: Install and check MariaDB client (macOS)
      if: runner.os == 'macOS' && ((matrix.config.mysql_client == '' ) || ! matrix.config.mysql_client)
      run: |
        brew install mariadb-connector-c
        mariadb_config
      shell: bash

    - name: Install MySQL client (macOS)
      if: runner.os == 'macOS' && ((matrix.config.mysql_client != '' ) || matrix.config.mysql_client)
      run: |
        brew install mysql-client
        echo PATH="/usr/local/opt/mysql-client/bin:${PATH}" | tee -a $GITHUB_ENV
        echo PKG_CONFIG_PATH="/usr/local/opt/mysql-client/lib/pkgconfig" | tee -a $GITHUB_ENV
      shell: bash

    - name: Check MySQL client (macOS)
      if: runner.os == 'macOS' && ((matrix.config.mysql_client != '' ) || matrix.config.mysql_client)
      run: |
        echo $PATH
        which mysql_config
        mysql_config || true
      shell: bash

    - name: Install and check MariaDB client (Linux)
      if: runner.os == 'Linux' && ((matrix.config.mysql_client == '' ) || ! matrix.config.mysql_client)
      run: |
        sudo apt purge -y libmysqlclient-dev
        sudo apt install -y libmariadb-dev
        mariadb_config
      shell: bash
