name: "Actions to compute a matrix with all suggested packages"
outputs:
  matrix:
    description: "Generated matrix"
    value: ${{ steps.set-matrix.outputs.matrix }}

runs:
  using: "composite"
  steps:
    - id: set-matrix
      run: |
        # Determine package dependencies
        if (!requireNamespace("desc", quietly = TRUE)) {
          install.packages("desc")
        }

        deps_df <- desc::desc_get_deps()
        deps_df <- deps_df[deps_df$type %in% c("Suggests", "Enhances"), ]

        packages <- sort(deps_df$package)
        packages <- intersect(packages, rownames(available.packages()))

        json <- paste0(
          '{"package":[',
          paste0('"', packages, '"', collapse = ","),
          ']}'
        )
        writeLines(json)
        writeLines(paste0("matrix=", json), Sys.getenv("GITHUB_OUTPUT"))
      shell: Rscript {0}
